# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-16 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaftarSiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama_Lengkap', models.CharField(max_length=50)),
                ('Tempat_Lahir', models.CharField(max_length=30)),
                ('Tanggal_Lahir', models.DateField()),
                ('Jenis_Kelamin', models.CharField(choices=[('pria', 'Pria'), ('wanita', 'Wanita')], default='pria', max_length=10)),
                ('Alamat', models.CharField(max_length=50)),
                ('Agama', models.CharField(max_length=20)),
                ('Nama_Orang_Tua', models.CharField(max_length=50)),
                ('Alamat_Orang_Tua', models.CharField(max_length=50)),
                ('No_Telp_Orang_Tua', models.CharField(max_length=13)),
            ],
        ),
    ]
