# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-31 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeri',
            options={'verbose_name': 'Tabel Galeri', 'verbose_name_plural': 'Tabel Galeri'},
        ),
    ]
