# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-16 13:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelGuru',
            fields=[
                ('NIK', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('Nama_Lengkap', models.CharField(max_length=50)),
                ('Nama_Panggilan', models.CharField(max_length=20)),
                ('Tempat_Lahir', models.CharField(max_length=25)),
                ('Tanggal_Lahir', models.DateField(max_length=50)),
                ('Tahun_Masuk', models.CharField(default='1999', max_length=4)),
                ('Alamat', models.CharField(max_length=60)),
                ('Jabatan', models.CharField(max_length=15)),
                ('Status', models.CharField(max_length=15)),
                ('No_Telp', models.CharField(max_length=13)),
                ('Motto', models.CharField(max_length=255)),
                ('Foto', models.FileField(blank=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TabelSiswa',
            fields=[
                ('NIS', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Nama_Lengkap', models.CharField(max_length=50)),
                ('Nama_Panggilan', models.CharField(max_length=20)),
                ('Tempat_Lahir', models.CharField(default='Tangerang', max_length=25)),
                ('Tanggal_Lahir', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
