# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-16 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelsiswa',
            name='Agama',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tabelsiswa',
            name='Alamat',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='tabelsiswa',
            name='Alamat_Orang_Tua',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='tabelsiswa',
            name='Anak_Ke',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tabelsiswa',
            name='Berat_Badan',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tabelsiswa',
            name='Nama_Orang_Tua',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabelsiswa',
            name='No_Telp_Orang_Tua',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='tabelsiswa',
            name='Tinggi_Badan',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tabelsiswa',
            name='Tempat_Lahir',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
