# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-16 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0003_pengembangan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('Kode_Kelas', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('Nama_Kelas', models.CharField(max_length=5)),
                ('Nama_Guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.TabelGuru')),
            ],
        ),
    ]
