# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-16 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0004_kelas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kelas',
            old_name='Nama_Guru',
            new_name='NIK_Guru',
        ),
    ]
