# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-16 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0005_auto_20190716_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penilaian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Penilaian', models.TextField()),
                ('Kode_Pengembangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.Pengembangan')),
                ('NIS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.TabelSiswa')),
            ],
        ),
    ]
