# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-16 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0006_penilaian'),
    ]

    operations = [
        migrations.RenameField(
            model_name='penilaian',
            old_name='NIS',
            new_name='Nama_Siswa',
        ),
    ]
