# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-16 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0007_auto_20190716_2138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TabelGuru',
            new_name='Guru',
        ),
        migrations.RenameField(
            model_name='kelas',
            old_name='NIK_Guru',
            new_name='Guru',
        ),
    ]
