# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-16 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0008_auto_20190716_2144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kelas',
            new_name='Kelas_Siswa',
        ),
        migrations.RenameModel(
            old_name='Pengembangan',
            new_name='Pengembangan_Siswa',
        ),
        migrations.RenameModel(
            old_name='Penilaian',
            new_name='Penilaian_Siswa',
        ),
        migrations.RenameModel(
            old_name='TabelSiswa',
            new_name='Siswa',
        ),
    ]
