# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-17 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0009_auto_20190716_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='Kelas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='akademik.Kelas_Siswa'),
        ),
    ]
