# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-17 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0010_siswa_kelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='Status',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('TA', 'Tidak Aktif')], default='Aktif', max_length=10),
        ),
    ]
