# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-17 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0012_siswa_jenis_kelamin'),
    ]

    operations = [
        migrations.AddField(
            model_name='guru',
            name='Jenis_Kelamin',
            field=models.CharField(choices=[('P', 'Pria'), ('W', 'Wanita')], default='P', max_length=10),
        ),
    ]
