# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-17 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0013_guru_jenis_kelamin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengembangan_siswa',
            name='Deskripsi',
            field=models.TextField(null=True),
        ),
    ]
