# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-18 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0014_pengembangan_siswa_deskripsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='Pekerjaan_Orang_Tua',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
