# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-18 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0015_siswa_pekerjaan_orang_tua'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelas_siswa',
            name='Keterangan',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
