# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-19 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0016_kelas_siswa_keterangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='Foto',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
