# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-30 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0017_auto_20190719_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='NilaiGuru',
            fields=[
                ('Kode_Nilai', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Judul_Penilaian', models.CharField(max_length=50)),
                ('Deskripsi', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PenilaianGuru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Penilaian', models.IntegerField()),
                ('NIK_Guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.Guru')),
                ('Nilai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.NilaiGuru')),
            ],
        ),
    ]
