# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-30 06:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0018_nilaiguru_penilaianguru'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guru',
            options={'verbose_name': 'Tabel Guru', 'verbose_name_plural': 'Tabel Guru'},
        ),
    ]
