# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-30 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0019_auto_20190730_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kelas_siswa',
            options={'verbose_name': 'Tabel Kelas Siswa', 'verbose_name_plural': 'Tabel Kelas Siswa'},
        ),
        migrations.AlterModelOptions(
            name='nilaiguru',
            options={'verbose_name': 'Tabel Nilai Guru', 'verbose_name_plural': 'Tabel Nilai Guru'},
        ),
        migrations.AlterModelOptions(
            name='pengembangan_siswa',
            options={'verbose_name': 'Tabel Pengembangan Siswa', 'verbose_name_plural': 'Tabel Pengembangan Siswa'},
        ),
        migrations.AlterModelOptions(
            name='penilaian_siswa',
            options={'verbose_name': 'Tabel Penilaian Siswa', 'verbose_name_plural': 'Tabel Penilaian Siswa'},
        ),
        migrations.AlterModelOptions(
            name='penilaianguru',
            options={'verbose_name': 'Tabel Penilaian Guru', 'verbose_name_plural': 'Tabel Penilaian Guru'},
        ),
        migrations.AlterModelOptions(
            name='siswa',
            options={'verbose_name': 'Tabel Siswa', 'verbose_name_plural': 'Tabel Siswa'},
        ),
    ]
