# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-30 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0020_auto_20190730_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kelas_siswa',
            options={'verbose_name': 'Tabel Siswa (Kelas Siswa)', 'verbose_name_plural': 'Tabel Siswa (Kelas Siswa)'},
        ),
        migrations.AlterModelOptions(
            name='nilaiguru',
            options={'verbose_name': 'Tabel Guru (Nilai Guru)', 'verbose_name_plural': 'Tabel Guru (Nilai Guru)'},
        ),
        migrations.AlterModelOptions(
            name='pengembangan_siswa',
            options={'verbose_name': 'Tabel Siswa (Pengembangan Siswa)', 'verbose_name_plural': 'Tabel Siswa (Pengembangan Siswa)'},
        ),
        migrations.AlterModelOptions(
            name='penilaian_siswa',
            options={'verbose_name': 'Tabel Siswa (Penilaian Siswa)', 'verbose_name_plural': 'Tabel Siswa (Penilaian Siswa)'},
        ),
        migrations.AlterModelOptions(
            name='penilaianguru',
            options={'verbose_name': 'Tabel Guru (Penilaian Guru)', 'verbose_name_plural': 'Tabel Guru (Penilaian Guru)'},
        ),
    ]
