# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-30 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0021_auto_20190730_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='penilaianguru',
            old_name='Nilai',
            new_name='Indikator',
        ),
        migrations.RenameField(
            model_name='penilaianguru',
            old_name='NIK_Guru',
            new_name='Nama_Guru',
        ),
    ]
