# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-31 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0022_auto_20190730_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabunganSiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tanggal', models.DateField()),
                ('Jumlah', models.IntegerField()),
                ('Kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.Kelas_Siswa')),
                ('Nama_Siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.Siswa')),
            ],
            options={
                'verbose_name': 'Tabel Siswa (Tabungan Siswa)',
                'verbose_name_plural': 'Tabel Siswa (Tabungan Siswa)',
            },
        ),
    ]
