# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-02 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0026_auto_20190802_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siswa',
            name='user',
        ),
    ]
