# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-02 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0028_siswa_angkatan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabungansiswa',
            name='Nama_Siswa',
        ),
        migrations.AddField(
            model_name='penilaianguru',
            name='Bulan',
            field=models.CharField(choices=[('Jan', 'Januari'), ('Feb', 'Februari'), ('Mar', 'Maret'), ('Apr', 'April'), ('Mei', 'Mei'), ('Jun', 'Juni'), ('Jul', 'Juli'), ('Agus', 'Agustus'), ('Sept', 'September'), ('Okt', 'Oktober'), ('Nov', 'November'), ('Des', 'Desember')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='Angkatan',
            field=models.CharField(choices=[('Ganjil 18/19', 'Ganjil 18/19'), ('Genap 18/19', 'Genap 18/19')], max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='TabunganSiswa',
        ),
    ]
