# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-05 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0030_auto_20190804_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPP_Siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bulan', models.CharField(choices=[('Jan', 'Januari'), ('Feb', 'Februari'), ('Mar', 'Maret'), ('Apr', 'April'), ('Mei', 'Mei'), ('Jun', 'Juni'), ('Jul', 'Juli'), ('Agus', 'Agustus'), ('Sept', 'September'), ('Okt', 'Oktober'), ('Nov', 'November'), ('Des', 'Desember')], max_length=15)),
                ('Tanggal', models.DateField(auto_now_add=True)),
                ('Nama_Siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.Siswa')),
            ],
            options={
                'verbose_name': 'Tabel Siswa (Pembayaran SPP Siswa)',
                'verbose_name_plural': 'Tabel Siswa (Pembayaran SPP Siswa)',
            },
        ),
    ]
