# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-05 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0031_spp_siswa'),
    ]

    operations = [
        migrations.AddField(
            model_name='spp_siswa',
            name='Keterangan',
            field=models.CharField(blank=True, choices=[('Lunas', 'Lunas'), ('Belum Lunas', 'Belum Lunas')], max_length=15, null=True),
        ),
    ]
