# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-05 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0032_spp_siswa_keterangan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kalender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tanggal', models.DateField()),
                ('Kegiatan', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Tabel Kalender Akademik',
                'verbose_name_plural': 'Tabel Kalender Akademik',
            },
        ),
    ]
