# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-22 15:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('akademik', '0033_kalender'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='Siswa',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
