# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-22 16:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('akademik', '0034_siswa_siswa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penilaian_siswa',
            name='Nama_Siswa',
        ),
        migrations.AddField(
            model_name='penilaian_siswa',
            name='Siswa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
