# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-23 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0036_auto_20190822_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='penilaian_siswa',
            name='Deskripsi',
            field=models.TextField(null=True),
        ),
    ]
