# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-24 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0037_penilaian_siswa_deskripsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penilaian_siswa',
            name='Bulan',
            field=models.CharField(choices=[('Januari Minggu 1', 'Januari M1'), ('Januari Minggu 2', 'Januari M2'), ('Januari Minggu 3', 'Januari M3'), ('Januari Minggu 4', 'Januari M4'), ('Februari Minggu 1', 'Februari M1'), ('Februari Minggu 2', 'Februari M2'), ('Februari Minggu 3', 'Februari M3'), ('Februari Minggu 4', 'Februari M4'), ('Maret Minggu 1', 'Maret M1'), ('Maret Minggu 2', 'Maret M2'), ('Maret Minggu 3', 'Maret M3'), ('Maret Minggu 4', 'Maret M4'), ('April Minggu 1', 'April M1'), ('April Minggu 2', 'April M2'), ('April Minggu 3', 'April M3'), ('April Minggu 4', 'April M4'), ('Mei Minggu 1', 'Mei M1'), ('Mei Minggu 2', 'Mei M2'), ('Mei Minggu 3', 'Mei M3'), ('Mei Minggu 4', 'Mei M4'), ('Juni Minggu 1', 'Juni M1'), ('Juni Minggu 2', 'Juni M2'), ('Juni Minggu 3', 'Juni M3'), ('Juni Minggu 4', 'Juni M4'), ('Juli Minggu 1', 'Juli M1'), ('Juli Minggu 2', 'Juli M2'), ('Juli Minggu 3', 'Juli M3'), ('Juli Minggu 4', 'Juli M4'), ('Agustus Minggu 1', 'Agustus M1'), ('Agustus Minggu 2', 'Agustus M2'), ('Agustus Minggu 3', 'Agustus M3'), ('Agustus Minggu 4', 'Agustus M4'), ('September Minggu 1', 'September M1'), ('September Minggu 2', 'September M2'), ('September Minggu 3', 'September M3'), ('September Minggu 4', 'September M4'), ('Oktober Minggu 1', 'Oktober M1'), ('Oktober Minggu 2', 'Oktober M2'), ('Oktober Minggu 3', 'Oktober M3'), ('Oktober Minggu 4', 'Oktober M4'), ('November Minggu 1', 'November M1'), ('November Minggu 2', 'November M2'), ('November Minggu 3', 'November M3'), ('November Minggu 4', 'November M4'), ('Desember Minggu 1', 'Desember M1'), ('Desember Minggu 2', 'Desember M2'), ('Desember Minggu 3', 'Desember M3'), ('Desember Minggu 4', 'Desember M4')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='penilaianguru',
            name='Bulan',
            field=models.CharField(choices=[('Januari', 'Januari'), ('Februari', 'Februari'), ('Maret', 'Maret'), ('April', 'April'), ('Mei', 'Mei'), ('Juni', 'Juni'), ('Juli', 'Juli'), ('Agustus', 'Agustus'), ('September', 'September'), ('Oktober', 'Oktober'), ('November', 'November'), ('Desember', 'Desember')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='spp_siswa',
            name='Bulan',
            field=models.CharField(choices=[('Januari', 'Januari'), ('Februari', 'Februari'), ('Maret', 'Maret'), ('April', 'April'), ('Mei', 'Mei'), ('Juni', 'Juni'), ('Juli', 'Juli'), ('Agustus', 'Agustus'), ('September', 'September'), ('Oktober', 'Oktober'), ('November', 'November'), ('Desember', 'Desember')], max_length=15),
        ),
    ]
