# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-24 21:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0038_auto_20190825_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='Anak_Ke',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
