# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-24 21:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0039_auto_20190825_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penilaianguru',
            name='Penilaian',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='Berat_Badan',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='Tinggi_Badan',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(150)]),
        ),
    ]
