# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-03 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sejarah',
        ),
        migrations.DeleteModel(
            name='Visimisi',
        ),
    ]
